// constants/districts.ts

export const DISTRICTS: Record<number, { label: string; value: string }[]> = {
    1: [
      { label: 'Seyhan', value: 'Seyhan' },
      { label: 'Yüreğir', value: 'Yüreğir' },
      { label: 'Çukurova', value: 'Çukurova' },
      { label: 'Sarıçam', value: 'Sarıçam' },
      { label: 'Ceyhan', value: 'Ceyhan' },
      { label: 'Kozan', value: 'Kozan' },
      { label: 'Karataş', value: 'Karataş' },
      { label: 'Feke', value: 'Feke' },
      { label: 'Pozantı', value: 'Pozantı' },
      { label: 'Tufanbeyli', value: 'Tufanbeyli' },
      { label: 'Aladağ', value: 'Aladağ' },
      { label: 'İmamoğlu', value: 'İmamoğlu' },
      { label: 'Yumurtalık', value: 'Yumurtalık' },
    ],
  
    2: [
      { label: 'Merkez', value: 'Merkez' },
      { label: 'Kahta', value: 'Kahta' },
      { label: 'Besni', value: 'Besni' },
      { label: 'Gölbaşı', value: 'Gölbaşı' },
      { label: 'Gerger', value: 'Gerger' },
      { label: 'Samsat', value: 'Samsat' },
      { label: 'Tut', value: 'Tut' },
      { label: 'Çelikhan', value: 'Çelikhan' },
    ],
  
    3: [
      { label: 'Merkez', value: 'Merkez' },
      { label: 'Sandıklı', value: 'Sandıklı' },
      { label: 'Dinar', value: 'Dinar' },
      { label: 'Bolvadin', value: 'Bolvadin' },
      { label: 'Emirdağ', value: 'Emirdağ' },
      { label: 'Şuhut', value: 'Şuhut' },
      { label: 'Çay', value: 'Çay' },
      { label: 'İhsaniye', value: 'İhsaniye' },
      { label: 'Sinanpaşa', value: 'Sinanpaşa' },
      { label: 'Sultandağı', value: 'Sultandağı' },
      { label: 'Başmakçı', value: 'Başmakçı' },
      { label: 'Bayat', value: 'Bayat' },
      { label: 'İscehisar', value: 'İscehisar' },
      { label: 'Dazkırı', value: 'Dazkırı' },
      { label: 'Evciler', value: 'Evciler' },
      { label: 'Hocalar', value: 'Hocalar' },
      { label: 'Kızılören', value: 'Kızılören' },
    ],
  
    6: [
      { label: 'Çankaya', value: 'Çankaya' },
      { label: 'Keçiören', value: 'Keçiören' },
      { label: 'Yenimahalle', value: 'Yenimahalle' },
      { label: 'Mamak', value: 'Mamak' },
      { label: 'Etimesgut', value: 'Etimesgut' },
      { label: 'Sincan', value: 'Sincan' },
      { label: 'Altındağ', value: 'Altındağ' },
      { label: 'Pursaklar', value: 'Pursaklar' },
      { label: 'Gölbaşı', value: 'Gölbaşı' },
      { label: 'Polatlı', value: 'Polatlı' },
      { label: 'Beypazarı', value: 'Beypazarı' },
      { label: 'Elmadağ', value: 'Elmadağ' },
      { label: 'Haymana', value: 'Haymana' },
      { label: 'Kızılcahamam', value: 'Kızılcahamam' },
      { label: 'Nallıhan', value: 'Nallıhan' },
      { label: 'Şereflikoçhisar', value: 'Şereflikoçhisar' },
      { label: 'Akyurt', value: 'Akyurt' },
      { label: 'Ayaş', value: 'Ayaş' },
      { label: 'Bala', value: 'Bala' },
      { label: 'Çamlıdere', value: 'Çamlıdere' },
      { label: 'Çubuk', value: 'Çubuk' },
      { label: 'Evren', value: 'Evren' },
      { label: 'Güdül', value: 'Güdül' },
      { label: 'Kalecik', value: 'Kalecik' },
      { label: 'Kazan', value: 'Kazan' },
    ],
  
    16: [
      { label: 'Osmangazi', value: 'Osmangazi' },
      { label: 'Nilüfer', value: 'Nilüfer' },
      { label: 'Yıldırım', value: 'Yıldırım' },
      { label: 'İnegöl', value: 'İnegöl' },
      { label: 'Gemlik', value: 'Gemlik' },
      { label: 'Mudanya', value: 'Mudanya' },
      { label: 'Karacabey', value: 'Karacabey' },
      { label: 'Mustafakemalpaşa', value: 'Mustafakemalpaşa' },
      { label: 'Orhangazi', value: 'Orhangazi' },
      { label: 'Yenişehir', value: 'Yenişehir' },
      { label: 'Kestel', value: 'Kestel' },
      { label: 'Gürsu', value: 'Gürsu' },
      { label: 'Büyükorhan', value: 'Büyükorhan' },
      { label: 'Harmancık', value: 'Harmancık' },
      { label: 'Keles', value: 'Keles' },
      { label: 'Orhaneli', value: 'Orhaneli' },
    ],
  
    34: [
      { label: 'Esenler', value: 'Esenler' },
      { label: 'Bağcılar', value: 'Bağcılar' },
      { label: 'Avcılar', value: 'Avcılar' },
      { label: 'Bahçelievler', value: 'Bahçelievler' },
      { label: 'Bakırköy', value: 'Bakırköy' },
      { label: 'Bayrampaşa', value: 'Bayrampaşa' },
      { label: 'Beşiktaş', value: 'Beşiktaş' },
      { label: 'Beylikdüzü', value: 'Beylikdüzü' },
      { label: 'Beyoğlu', value: 'Beyoğlu' },
      { label: 'Büyükçekmece', value: 'Büyükçekmece' },
      { label: 'Esenyurt', value: 'Esenyurt' },
      { label: 'Fatih', value: 'Fatih' },
      { label: 'Gaziosmanpaşa', value: 'Gaziosmanpaşa' },
      { label: 'Kağıthane', value: 'Kağıthane' },
      { label: 'Küçükçekmece', value: 'Küçükçekmece' },
      { label: 'Sarıyer', value: 'Sarıyer' },
      { label: 'Silivri', value: 'Silivri' },
      { label: 'Şişli', value: 'Şişli' },
      { label: 'Zeytinburnu', value: 'Zeytinburnu' },
    ],
  
    341: [
      { label: 'Kadıköy', value: 'Kadıköy' },
      { label: 'Ümraniye', value: 'Ümraniye' },
      { label: 'Pendik', value: 'Pendik' },
      { label: 'Ataşehir', value: 'Ataşehir' },
      { label: 'Maltepe', value: 'Maltepe' },
      { label: 'Kartal', value: 'Kartal' },
      { label: 'Tuzla', value: 'Tuzla' },
      { label: 'Üsküdar', value: 'Üsküdar' },
      { label: 'Beykoz', value: 'Beykoz' },
      { label: 'Sancaktepe', value: 'Sancaktepe' },
      { label: 'Sultanbeyli', value: 'Sultanbeyli' },
      { label: 'Çekmeköy', value: 'Çekmeköy' },
      { label: 'Şile', value: 'Şile' },
    ],
  
    35: [
      { label: 'Konak', value: 'Konak' },
      { label: 'Bornova', value: 'Bornova' },
      { label: 'Karşıyaka', value: 'Karşıyaka' },
      { label: 'Buca', value: 'Buca' },
      { label: 'Bayraklı', value: 'Bayraklı' },
      { label: 'Gaziemir', value: 'Gaziemir' },
      { label: 'Balçova', value: 'Balçova' },
      { label: 'Çiğli', value: 'Çiğli' },
      { label: 'Karabağlar', value: 'Karabağlar' },
      { label: 'Menemen', value: 'Menemen' },
      { label: 'Torbalı', value: 'Torbalı' },
      { label: 'Aliağa', value: 'Aliağa' },
      { label: 'Kemalpaşa', value: 'Kemalpaşa' },
      { label: 'Tire', value: 'Tire' },
      { label: 'Ödemiş', value: 'Ödemiş' },
      { label: 'Selçuk', value: 'Selçuk' },
      { label: 'Menderes', value: 'Menderes' },
      { label: 'Seferihisar', value: 'Seferihisar' },
      { label: 'Urla', value: 'Urla' },
      { label: 'Foça', value: 'Foça' },
      { label: 'Dikili', value: 'Dikili' },
      { label: 'Çeşme', value: 'Çeşme' },
      { label: 'Karaburun', value: 'Karaburun' },
      { label: 'Bergama', value: 'Bergama' },
      { label: 'Kınık', value: 'Kınık' },
      { label: 'Kiraz', value: 'Kiraz' },
      { label: 'Beydağ', value: 'Beydağ' },
    ],
  };
  